### ISSUE TITLE
Problem with Stripe webhook

### ISSUE THREAD

**Issue by catherinetenajeros** [pinax/pinax-stripe#101]
I got a mail from Stripe and they are having trouble delivering webhooks to my test webhook handler. I got HTTP status code of 403 when I test it. 

Response:

Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for same-origin' requests.

How can I fix this problem?

**Comment by gtournie** [comment]
in your controller, put:
```
protect_from_forgery except: :action_name
```

**Comment by paltman** [comment]
@catherinetenajeros wow, it's embarrassing that it's been 2+ years and I haven't responded to you. Many apologies.

The webhook view should not require CSRF tokens so I'm not sure what was going on. I doubt you are still having the problem at this point but if you are and still want my help, please reopen this issue with the link (relative is fine) you have configured in Stripe as well as your urls.py include. It sounds like it might be pointing to a different url.

**Comment by mrooney** [comment]
FWIW, I got here via Google because I thought I was experiencing this too. If it helps anyone, I had forgotten to add "/payments/webhook/" to my endpoint in Stripe :)
