### ISSUE TITLE
Stripe Charge Dispute Webhooks Are Not Handled Properly

### ISSUE THREAD

**Issue by almostabc** [pinax/pinax-stripe#104]
Stripe [charge.dispute.<verb>](https://stripe.com/docs/api#event_types) webhooks are not handled properly. These events describe a [dispute object](https://stripe.com/docs/api#update_dispute), but django-stripe-payments thinks they are describing a Charge object. As a result the data from the webhook is passed to the sync_from_stripe_data method of the Charge class, which causes a KeyError since dispute's don't have an "id".

**Comment by paltman** [comment]
@almostabc this should be resolved now on `master`
