### ISSUE TITLE
Cancelling a Customer Subscription

### ISSUE THREAD

**Issue by lightstrike** [pinax/pinax-stripe#119]
Is there a built-in way to cancel a customer's subscription in django-stripe-payments via https://stripe.com/docs/api/python#cancel_subscription? 

As far as I can tell, the delete method for CurrentSubscription just removes the object from the database and doesn't interact with the API in any way.

**Comment by paltman** [comment]
@lightstrike that's a good suggestion and I'll consider that for the next release.  many apologies for the tardiness of replies here. trying to get a better handle on how to better maintain 70+ open source projects with just a small core team.

**Comment by paltman** [comment]
This is now resolved with explicit path to cancel
