### ISSUE TITLE
Events being marked as Invalid, resulting in no processing of events

### ISSUE THREAD

**Issue by surfer26th** [pinax/pinax-stripe#121]
My events in the events table are all being marked as not valid, and therefore no events are being processed. Which means no notifications of any sort are being sent about anything, like invoice created, plans changed (from trial to subscription), etc. This critical problem doesn't seem to be reported by anyone else, so I'm suspicious about whether it's just me.

In looking at the objects in the table, I see that the webhook message['data'] appears to be slightly different than the Validated message['data']. Refer to this line in payments class Event, method validate (starting line 117 (in models.py): 

 if self.webhook_message["data"] == self.validated_message["data"]:
            self.valid = True
        else:
            self.valid = False

I used this nifty tool tlrobinson.net/projects/javascript-fun/jsondiff/‎
to compare the json data, and the difference seems to be this:

The Validated message includes the key "previous_metadata" in the values for Validated_message['data']; whereas, "previous_metadata" does not appear in the webhook message json.

In looking at stripe __.init__.py, I see that line 582 contains this within the class StripeObject:
    if 'metadata' in values:
      self.previous_metadata = values['metadata']

I am using stripe version 1.9.8  

Seems to be a simple fix. But before I do anything about it, anyone else see the same problem, or just me??

**Comment by paltman** [comment]
@surfer26th I wonder if this is still the case with all the changes just pushed to `master`. Please reopen if you can confirm it still is indeed a problem.
