### ISSUE TITLE
Indicate which Stripe API version this library is compatible with

### ISSUE THREAD

**Issue by frewsxcv** [pinax/pinax-stripe#151]
There are multiple version of the Stripe API

https://stripe.com/docs/upgrades

**Comment by caacree** [comment]
Seconded. I just started with Stripe, they automatically start people with the latest API, which is currently incompatible with django-stripe-payments. (For what it's worth, my current error is AttributeError on customer.active_card.fingerprint when calling the update_card method. )

Excerpt from the message from Stripe support:

I'm really sorry about the trouble: we did deploy a small change to when we decide to show fingerprints, but it was thoroughly tested to avoid changing any existing behavior. I suspect you being on a higher API version, but sending low Stripe-Version headers with every request (this is done by your django plugin), is a case we hadn't accounted for (very few people actually use Stripe-Version headers for older version).

**Comment by paltman** [comment]
You are right. Lots of work planned here. Just trying to find the time.

**Comment by frewsxcv** [comment]
For what it's worth, the project I'm using this library with is using the API version from `2014-06-17` and it seems to work alright

**Comment by lukeburden** [comment]
+1 on hitting issues with supported version of Stripe's API.

@paltman any estimate when the time might be found? There appear to be issues with the project's auto build and it's starting to feel a little unmaintained. I don't mean to apply pressure! Just pointing it out. :) If you've got a plan and can push a slice of the work my way, I'd be happy to give you a PR.

**Comment by wahuneke** [comment]
One thing that makes this really tricky, in my opinion is the processing of webhooks.

Outbound api calls to stripe can be forced to use a certain api version. django-stripe-payments already does this using the STRIPE_API_VERSION setting. As long as the default STRIPE_API_VERSION is correct and matches the implementation of outbound calls, I don't see why anyone would have any issues here...

Webhooks, on the other hand, big problem.  Webhooks are always sent using your Stripe account's API version. This means that django-stripe-payments will be processing webhook objects of completely 'random' structure and may not process them correctly.

Stripe does not let you set your account's api version!!!! They only let you upgrade to the latest version. This means django-stripe-payments users will almost never be using the right version on their webhook messages.

Strictly speaking, this is terrible. Practically speaking though, many people will probably get away with relatively error-free webhook processing.

I don't want to get into TLDR territory here... Has anyone else thought about this issue?

**Comment by paltman** [comment]
We now support [latest API version](https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/conf.py#L33).  Making this a setting is a little strange as to get to this point I had to refactor a lot of the modeling, so I don't think one can easily just set this setting to any old version and things just magically work. In addition, as @wahuneke pointed out it's important that it's in sync with what the webhooks are going to be sending.

**Comment by streeter** [comment]
Awesome! Thanks @paltman
