### ISSUE TITLE
Add Django Migrations

### ISSUE THREAD

**Issue by wahuneke** [pinax/pinax-stripe#164]
Sorry, this is a really obvious one but I couldn't find any documentation or mention anywhere, even in issues, about migrations and south.

So this is really more of a question: Why are there no migrations in this project? Will they be introduced at some point? Are you waiting to use Django native migrations (introduced in 1.7)? Maybe just waiting until you can declare 1.7 as minimum supported version?

It seems to me (and I'm sure to you too) that lack of migrations may be really holding back growth and development in the django-stripe-payments app.

I'm planning on adding (South-style) migrations in my fork, but it would be nice to know _your_ plan so I'll be able to push my work upstream some day.

Thanks!

**Comment by paltman** [comment]
@wahuneke Yes, we were waiting on all Pinax apps until minimum supported version of Django became 1.7 which is now is. I have marked this issue as inclusion for the 2.0 Milestone.
