### ISSUE TITLE
Support for ordering of payment plans

### ISSUE THREAD

**Issue by codydjango** [pinax/pinax-stripe#166]
PAYMENT_PLANS are currently a dictionary.  As a dict, the order of the plans can't be depended on.  To support ordering let's instead use ordereddict or a list with the plan key as another dict attribute.

**Comment by paltman** [comment]
@codydjango take a look at `pinax-stripe` now. I have changed a lot including the syncing of plans from Stripe rather than storage in a `dict` setting.

**Comment by ossanna16** [comment]
@paltman: Can this issue be closed?
