### ISSUE TITLE
Invoice migration error from 0001 to 0002

### ISSUE THREAD

**Issue by miketheredherring** [pinax/pinax-stripe#194]
The following error is generated when trying to perform migrations, on a clean schema, with PostgreSQL 9.3.5 and Django 1.8.4.

```python
Operations to perform:
  Apply all migrations: pinax_stripe
Running migrations:
  Rendering model states... DONE
  Applying pinax_stripe.0002_auto_20151121_2054...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)

  ... Very deep stack trace ...

  File "/Users/mikehearing/.virtualenvs/web/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "charge_id" cannot be cast automatically to type integer
HINT:  Specify a USING expression to perform the conversion.
```

It seems as though `Invoice.charge` was initially declared as a `CharField`, and PostgreSQL is having trouble converting to a `ForeignKey` due to the database type `character varying` -> `integer`.

Changing the `AlterField` to a sequential `RemoveField` and `AddField` in 0002 manually would resolve this issue. It looks like a data migration is required in either case, if you wanted to preserve this 'relationship' and create `Charge` objects.

**Comment by paltman** [comment]
This is interesting. I haven't not seen this in all my testing so thanks for the report! 

Good call on database migrations. I completely forgot about them.  the `0001` should be able to be `--fake-initial`'d  for prior versions, but need to obviously consider porting data.

That said, all the data is just a cache, so it might be cleaner to just start fresh.

In fact, now that I think about it, this isn't going to migrate old tables as old tables have `payments_` as a prefix while this will have `pinax_stripe_` for a prefix.

Hm....

**Comment by miketheredherring** [comment]
The only model I've noticed which is not a direct cache, and you'd might want to keep data for, would be the `Customer` since it provides the relationship to the `User` model within Django. Otherwise, I agree with starting from scratch, you could even run a squash migrations and remove the `Invoice.charge` from ever being a `CharField`.

I'm not familiar with how much backwards compatibility you are trying to maintain for `django-stripe-payments` users, or ease of migration to the new code; both of which will influence the solution here... I would be more than happy to provide a pull request if you could give me some direction with that regards?

**Comment by paltman** [comment]
Good call on the Customer <-> User relation.

I would like to provide a sane upgrade experience for existing users. To be honest though, I haven't thought much about it. I wanted to work out first getting things into a really good state and then step back and consider what an upgrade looks like.  I think most of the dust has settled now though. I expect some more changes in in the `pinax.stripe.actions.*` modules but nothing too drastic.

I'd love some help with it!

**Comment by paltman** [comment]
So I think we squash migrations to just a single `0001_initial` prior to releasing 2.0 and add a `0002_upgrade_data` migration that is:

* a noop for new installs where `payments_customer` table doesn't exist
* migrates the `payments_customer` data into `pinax_stripe_customer`

I don't think we should automatically run `sync_customers` as that could take a long time but should have a separate document about upgrading that covers:

* running migrations
* running `sync_customers`
* updating versions number of API that webhooks send (setup in Stripe panel)

**Comment by paltman** [comment]
bcbb700 adds the DSP migration
