### ISSUE TITLE
Plan object name is always in $ currency.

### ISSUE THREAD

**Issue by amnesic** [pinax/pinax-stripe#228]
Even if the Plan is in euro (€), the string representation of the Plan object will be to the form : 
"name ($ xx)" instead of  "name (€ xx)"

https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/models.py#L35

**Comment by paltman** [comment]
nice catch @amnesic!

**Comment by paltman** [comment]
This should be a relatively easy fix.  We just need to have a mapping of currency symbols to their codes.

**Comment by ossanna16** [comment]
Would this be a good "difficulty: easy" issue?

**Comment by paltman** [comment]
http://www.xe.com/symbols.php

Using the last column you can get the symbols "unicode hex":

```python
print("\u0024")  # $
```

**Comment by paltman** [comment]
so i'm thinking a dict of something like:

```python
currencies = {
    "usd": "\u0024",
    "vnd": "\u20ab"
}
```

To just list two examples.
