### ISSUE TITLE
Migration Circular Dependency Error

### ISSUE THREAD

**Issue by mosesmc52** [pinax/pinax-stripe#230]
Hi, 

I'm trying to run an initial migration with pinax-stripe installed in my django application, but this error occurs. How could I fix it. 

    raise CircularDependencyError(", ".join("%s.%s" % n for n in cycle))
django.db.migrations.graph.CircularDependencyError: pinax_stripe.0001_initial, app.0001_initial, pinax_stripe.0002_auto_20151205_1451

**Comment by mosesmc52** [comment]
The issue with this migration is that I have a model field within my application that I store the pinax-stripe customer model.

**Comment by mosesmc52** [comment]
I fixed my own issue. I removed the model field and replaced it with a character field inserting the stripe id.

**Comment by ossanna16** [comment]
Awesome 👍
