### ISSUE TITLE
Add migrations to Getting Started

### ISSUE THREAD

**Issue by mwarkentin** [pinax/pinax-stripe#236]
I didn't see anything about running migrations after installing pinax-stripe, but it appears there are some (assuming they need to be run before I sync my plans from Stripe):

```
pinax_stripe
 [ ] 0001_initial
 [ ] 0002_auto_20151205_1451
```

**Comment by ossanna16** [comment]
@mwarkentin Is this missing in the docs? If yes, would you mind submitting a patch? I'd appreciate it 😊

**Comment by mwarkentin** [comment]
Can do. :)

**Comment by ossanna16** [comment]
Thanks a ton! You're awesome!

**Comment by mwarkentin** [comment]
@ossanna16 Done. ^^

**Comment by ossanna16** [comment]
@mwarkentin That was super quick, thank you! :) Merging as soon as the checks are completed.
