### ISSUE TITLE
Templates are not added in pip package

### ISSUE THREAD

**Issue by JosPolfliet** [pinax/pinax-stripe#243]
I installed using 'pip install pinax-stripe'. The default template directory is empty, except for some emails. This causes TemplateDoesNotExist errors when trying the default views.

Only templates succesfully included are e-mail templates:
```
find (venv folder)/local/lib/python2.7/site-packages/pinax/stripe/templates -type f
(venv folder)/local/lib/python2.7/site-packages/pinax/stripe/templates/pinax/stripe/email/body_base.txt
(venv folder)/local/lib/python2.7/site-packages/pinax/stripe/templates/pinax/stripe/email/subject.txt
(venv folder)/local/lib/python2.7/site-packages/pinax/stripe/templates/pinax/stripe/email/body.txt
```

**Comment by mwarkentin** [comment]
@JosPolfliet Take a look at https://github.com/pinax/pinax-theme-bootstrap 

This is a bit of a dupe of #242 - one of these should probably stay open until the docs can be updated.

**Comment by JosPolfliet** [comment]
Thanks. Should have done more research. Indeed the documentation should be updated. My personal opinion is that standard templates are a good thing, even if they are crappy. It gives you a minimum working example which you then can start to extend..

**Comment by ossanna16** [comment]
@JosPolfliet We would appreciate if you'd make a PR for adding this to the docs :)
