### ISSUE TITLE
Docs refer to `PINAX_STRIPE_PRIVATE_KEY`

### ISSUE THREAD

**Issue by RevolutionTech** [pinax/pinax-stripe#254]
The docs refer to `PINAX_STRIPE_PRIVATE_KEY` in the Getting Started section, when it seems that `PINAX_STRIPE_SECRET_KEY` was intended.

A small thing, but it tripped me up for about 30 minutes, trying to figure out what I had wrong.

**Comment by ossanna16** [comment]
@paltman Can you confirm this?

**Comment by camdenb** [comment]
I can confirm this -- `PINAX_STRIPE_SECRET_KEY` is intended.
