### ISSUE TITLE
email charge notification not rendering properly

### ISSUE THREAD

**Issue by mackinnon3540** [pinax/pinax-stripe#260]
It appears the Charge model doesn't record the last 4 digits of the card charged, and as a result the context variable {{ charge.card_last_4 }}  in body_base.txt is empty. Perhaps in charges.py, you could capture this data in the stripe json response by adding the following line of code:
obj.last4 = data["source"]["last4"] 
and also adding that field to the Charge model. 
Also, I'm getting duplicate email notifications for a single stripe subscription  charge.   Any thoughts on what's causing it? Thanks!

**Comment by ossanna16** [comment]
@paltman Can you please help with this?

**Comment by paltman** [comment]
We should add a property on the `Charge` model:

```python
@property
def card(self):
    return Card.objects.filter(stripe_id=self.source).first()
```

Then in the email template we change `{{ charge.card_last_4 }}` to `{{ charge.card.last4 }}`.

We can worry about other sources later.
