### ISSUE TITLE
Associate Stripe Customers with Teams instead of Users

### ISSUE THREAD

**Issue by irothschild** [pinax/pinax-stripe#264]
Currently Stripe Customers (and subscriptions, payments etc.) are linked to Users. It would be good if they could be linked to Teams (which could represent a company or organization.) Has anyone done that?

**Comment by ossanna16** [comment]
@paltman Can you help with this?

**Comment by paltman** [comment]
@irothschild In Stripe, a `Customer` is intended to represent a *user*.  It has things like `email` and `sources` (Payment Sources), linked to it.

I think it would be better to model the relationship in your project of a team/organization to a particular customer who was the card holder.
