### ISSUE TITLE
Better docs on webhooks

### ISSUE THREAD

**Issue by jhanda1** [pinax/pinax-stripe#265]
Not sure the proper way to go about this and I can't find any docs or examples that seem relevant.  Specifically, I need to add some functionality to invoice.payment_succeeded and invoice.payment_failed.  Not sure if I need to override the webhook methods or catch signals for those events or what..

**Comment by ossanna16** [comment]
@paltman  ^

**Comment by paltman** [comment]
@jhanda1 yes, we should add documentation for this under webhooks section of the docs (#217).

In short, you'll want to set up a receiver for the `invoice.payment_succeeded` event.  I haven't tested the code but it would be something like:

```python
from django.dispatch import receiver

from pinax.stripe.signals import WEBHOOK_SIGNALS


@receiver(WEBHOOK_SIGNALS["invoice.payment_succeeded"])
def handle_payment_succeeded(sender, event, **kwargs):
    pass  # do what it is you want to do here
```

the event object is a [`models.Event`](https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/models.py#L55) instance with all the data necessary to do what you want to do.
