### ISSUE TITLE
Possible bug with changing subscription name

### ISSUE THREAD

**Issue by johndark** [pinax/pinax-stripe#276]
Hi,
just changed the name of subscription plan at Stripe and got a callback with:
`"type": "plan.updated", "name": "X-Small","previous_attributes": "name": "X-SMALL"`, but as I see in database, table `pinax_stripe_plan`, the field `name` didn't changed, it still has `X-SMALL` value.

**Comment by johndark** [comment]
Same for new plan created, got a callback to my app with `plan.created` but don't see new plan in database.
Not sure, maybe b/c it's `"livemode": false`?

**Comment by ossanna16** [comment]
@paltman Can you help with this?

**Comment by paltman** [comment]
We probably want to add a handler for the events: `plan.updated` and `plan.created`  which will mean adding `process_webhook` methods to [`PlanUpdatedWebhook` and `PlanCreatedWebhook`](https://github.com/pinax/pinax-stripe/blob/master/pinax/stripe/webhooks.py#L410-L417).

We'll probably want to add another function in `actions/plans.py` that syncs an individual plan to call within the webhook handling customization.  Perhaps called something like `sync_plan`.
