### ISSUE TITLE
Charge.create method requires customer when stripe does not 

### ISSUE THREAD

**Issue by adamduren** [pinax/pinax-stripe#306]
Trying to use `actions.charges.create()` in this invocation `charges.create(amount=total, customer=None, source=data['stripe_token'])`. The charge gets correctly created and displays in the Stripe admin but the code after the call to the stripe API crashes.

This is called after the stripe call:
```python
charge = sync_charge_from_stripe_data(stripe_charge)
```

Here is the top of code of that method:
```python
def sync_charge_from_stripe_data(data):
    customer = models.Customer.objects.get(stripe_id=data["customer"])
```

The crash is because of passing `None` into customer. Is there a reason `pinax-stripe` requires a `Customer` object to create a charge?

**Comment by adamduren** [comment]
Following along the code. It seems like the only use for the customer is in the next lines of that method:
```python
    obj, _ = models.Charge.objects.get_or_create(
        customer=customer,
        stripe_id=data["id"]
    )
```

The interesting thing is from reading the code I believe the `stripe_id` should always be unique so why is the `customer` object needed?

**Comment by blueyed** [comment]
As per https://stripe.com/docs/api#create_charge-customer either a `customer` or `source` is required.

See https://github.com/pinax/pinax-stripe/pull/460 for an improvement to this.
