### ISSUE TITLE
InvoiceItem model has two fields named quantity

### ISSUE THREAD

**Issue by JimmyVT** [pinax/pinax-stripe#318]
I'm not that familiar with Stripe's API, but I believe the one that should remain is the IntegerField and not the PositiveIntegerField ... Am I correct in assuming this?

**Comment by iarp** [comment]
You're right, django takes the last one listed top to bottom. Looking at the migrations you can also see PositiveIntergerField has never been used

**Comment by JimmyVT** [comment]
That's good to know ! Thank you!

**Comment by paltman** [comment]
Thanks for catching this.  We'll remove the extra one.
