### ISSUE TITLE
Expected date for new release?

### ISSUE THREAD

**Issue by xfxf** [pinax/pinax-stripe#328]
Apologies if this is the wrong spot for this; I can't think of a more appropriate place to put it.  There is increasing functionality only available in current master we're relying on for a production system (coupons, tax_percent for subscriptions) and it'd be lovely to get a new release cut.

Last release was 6 months ago.

**Comment by paltman** [comment]
You are right. I'll try to get a release out this weekend. Thanks!

**Comment by paltman** [comment]
@xfxf finally done.  the release is fast.  it's authoring the release notes that takes some time. :)

https://github.com/pinax/pinax-stripe/releases/tag/v3.4.0
