### ISSUE TITLE
Caching of Stripe customer object / JSON

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#340]
Accessing `Customer.stripe_customer` triggers a refresh/GET through the Stripe API always.

https://github.com/pinax/pinax-stripe/blob/afe0eb63e1a426d99e64a289591d58832d6e9e23/pinax/stripe/models.py#L135 and then https://github.com/stripe/stripe-python/blob/94a11506040bde0506d7164b635603d50ccf6df0/stripe/resource.py#L337

I would like to add caching for this, so that it only gets updated through Stripe events.

Does this make sense?
Is it a supported use case after all?

The customer object / JSON is used with the standard iOS integration (https://stripe.com/docs/mobile/ios/standard).

**Comment by paltman** [comment]
Let's use `@cached_property` decorator on that property (`from django.utils.functional import cached_property`)

**Comment by blueyed** [comment]
@paltman 
Great.
Will you do it yourself?

**Comment by gregnewman** [comment]
@blueyed I'll take care of it :)
