### ISSUE TITLE
Integrity error 

### ISSUE THREAD

**Issue by peterglock** [pinax/pinax-stripe#344]
`customer.source.created events` give a web hook success. However,...

`invoice.created`, `invoice.payment_suceeded` and `charge.suceeded` events lead to an integrity error:

```
Exception Type: IntegrityError at /accounts/payments/webhook/
Exception Value: null value in column "customer_id" violates not-null constraint
DETAIL:  Failing row contains (34, ch_1AZf7GEpqJ8aOjuYYKi2vsvb, 2017-06-28 12:18:27.833096+00, , usd, null, null, , null, null, null, null, f, null, null, null).
```

The second entry in the row (ch_...) is the Stripe customer id.

I'm using latest Stripe API, Django 1.11.2, pinax-stripe 3.4.1

How to debug?

**Comment by paltman** [comment]
`ch_1AZf7GEpqJ8aOjuYYKi2vsvb` would indicate an id for a `Charge` not a `Customer`.  We need more details on this.

**Comment by spr0cketeer** [comment]
@peterglock I was hit by this bug too after upgrading to the latest pinax-stripe.  This commit https://github.com/pinax/pinax-stripe/pull/307 changed how charges are created and it contains a django model migration you need to apply with 'manage.py migrate' to remove the not-null constraint on the customer_id field in the Charge table.

**Comment by peterglock** [comment]
@spr0cketeer. I manually amended the charges table and fixed the problem a couple of weeks ago. The same change is also required for the invoices. All working now.
