### ISSUE TITLE
Enable simple payments without customer attribute on charges.create

### ISSUE THREAD

**Issue by JuanjoA** [pinax/pinax-stripe#348]
Hi, we need to use stripe.js (checkout) for simple payments, but the charges.create has the customer attribute required.

It's possible to do this with pinax-stripe?

Thanks!

**Comment by blueyed** [comment]
I think you can use `customer=None` already, but https://github.com/pinax/pinax-stripe/pull/460 makes it cleaner.

**Comment by JuanjoA** [comment]
Thanks @blueyed , I close this issue.
