### ISSUE TITLE
Install codecov integration

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#388]
@paltman 
https://github.com/integration/codecov

(see https://docs.codecov.io/v4.3.6/docs/team-bot)

**Comment by paltman** [comment]
I'm unsure of what that is actually for.  I read through the page it's unclear what that gives us as It seems like we already have integration:

https://github.com/pinax/pinax-stripe/pull/336#issuecomment-333685794

**Comment by blueyed** [comment]
That is the bot used as fallback, and is apparently currently buggy since it might comment multiple times.

**Comment by paltman** [comment]
Oh, I didn't realize.  I'll look into it (as well as turn the travis bits off.  Thanks for your continued help on this project!

**Comment by blueyed** [comment]
Hmm, having `codecov` as the comment author seems to be correct, at least according to what I see from another project.

**Comment by blueyed** [comment]
But you should turn off Travis indeed.

**Comment by paltman** [comment]
Phew, I thought I was going crazy. :)

**Comment by paltman** [comment]
I think the travis notifications should be off now.
