### ISSUE TITLE
Delete remote Stripe resources if model gets deleted?

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#393]
I think it might make sense to (optionally) delete remote resources, e.g. when deleting a Plan object.

**Comment by japrogramer** [comment]
could they instead be marked as expired in metadeta.

**Comment by blueyed** [comment]
So missing remote objects would get (possibly) recreated after you've deleted them, if there are events for them?
I agree.  Please close the issue then if I understood you correctly.
