### ISSUE TITLE
[connect] Charge/Invoice do not inherit from AccountRelatedStripeObject

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#425]
Invoices and Charges do not inherit from `AccountRelatedStripeObject`, but only take the account into consideration for the `stripe_invoice` and `stripe_charge` properties (using the customer):
https://github.com/pinax/pinax-stripe/blob/fda68d45cbd68a67ca0be9f5cf6edb46dcf9edc1/pinax/stripe/models.py#L364-L372
https://github.com/pinax/pinax-stripe/blob/fda68d45cbd68a67ca0be9f5cf6edb46dcf9edc1/pinax/stripe/models.py#L297-L306

@lukeburden 
Is there a reason for doing it like that?
Shouldn't they just derive from `AccountRelatedStripeObject` also?

**Comment by lukeburden** [comment]
It seemed overly redundant to me, as both `Invoice` and `Charge` models are already related to `Customer`, which is an `AccountRelatedStripeObject`.

**Comment by blueyed** [comment]
Fixed in 0799022c.
