### ISSUE TITLE
[connect] Account: add field for Stripe's publishable key

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#437]
The publishable key is required for clients to create tokens.

I think it makes sense to have a field for it on the Account object.

AFAIK there is no way to retrieve this, but it would have to be edited manually, e.g in the Django admin.

Ref: https://stripe.com/docs/dashboard#api-keys

/cc @lukeburden

**Comment by ticosax** [comment]
We have access to the publishable key when we create the account using OAuth flow.
https://stripe.com/docs/recipes/store-builder#connecting-accounts
I think it worth adding this field.

**Comment by lukeburden** [comment]
Makes sense to me - might be worth adding a mention in the docs of how and when to populate it.

**Comment by paltman** [comment]
How does this new field get populated?

**Comment by blueyed** [comment]
We're doing it in the OAuth flow, but it can be done manually also, e.g. in the admin.

**Comment by paltman** [comment]
Oh, I guess that is outside the scope of pinax-stripe (the OAuth flow).

What are you using for that?   python-social-auth?

**Comment by blueyed** [comment]
@ticosax did it, and plans to upstream it (later).

**Comment by blueyed** [comment]
IIRC it is nothing too fancy, but based on what they have documented basically.

**Comment by paltman** [comment]
@blueyed @ticosax I was about to write the oauth bits to include in pinax-stripe to make it simpler to integrate Standard form of Connect but if you already have something i'd love to just pull it in instead of duplicate the effort.
