### ISSUE TITLE
Failed syncdb with django-jsonfield. Installed jsonfield and it worked

### ISSUE THREAD

**Issue by surfer26th** [pinax/pinax-stripe#45]
Did a pip install django-stripe-payments. It automatically installed django-jsonfield. But trying to do a syncdb failed. I installed jsonfield==0.9.4 and was able to syncdb and tables created successfully.

**Comment by paltman** [comment]
@surfer26th have not been able to reproduce this across three versions of Django. please reopen if it is still an issue for you.
