### ISSUE TITLE
actions.charges.create: use customer object?!

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#462]
`actions.charges.create` uses `customer` as a string currently, but it would be better to have the object there, so that its `stripe_account` can be used.

Other actions like `invoices.create` or `refunds.create` use `customer` as an object already.

For backward compatibility it could handle both, but only document the object?!

**Comment by paltman** [comment]
Good catch.  Yes, for BC, I think we'd need to handle both, but only document the customer object.

**Comment by blueyed** [comment]
Addressed in https://github.com/pinax/pinax-stripe/pull/464.
