### ISSUE TITLE
webhooks: customer.created should create local Customer

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#467]
When you create a customer through the Stripe Dashboard, it sends the "customer.created" event, but pinax-stripe does not create the local Customer object then.

Do you agree?

**Comment by blueyed** [comment]
I think this could get handled in `link_customer` then, where it should also get ensured - i.e. a event with customer info should always link a customer, and create it if it does not exist.

**Comment by blueyed** [comment]
The tests are testing somehow the opposite though currently: https://github.com/pinax/pinax-stripe/blob/eb2a0557a1a1d2d860418eed084ca032d3301dd9/pinax/stripe/tests/test_webhooks.py#L346-L363

**Comment by blueyed** [comment]
Affects other events also, e.g. customer.subscription.updated.
We should allow for a customer to be deleted locally always, right?

**Comment by blueyed** [comment]
@paltman @lukeburden 
Any input on this?

**Comment by lukeburden** [comment]
If there's a customer, I think the local cache should know about it - so I'd be for properly adding a customer on receipt of a `customer.created` event. Worth noting it will be orphaned though, in the sense that it won't be associated with a local user.

I also agree that if a customer is deleted on Stripe's side, this deletion should be reflected in the local cache.

**Comment by blueyed** [comment]
What do you think about doing this in `link_customer` in general?

**Comment by lukeburden** [comment]
That seems reasonable to me.

We might need to see how it performs practically though? In one project I have, I currently get some weird race conditions around customer existence for source creation when making charges, which I haven't been able to work out yet. So I'm a little hesitant to create a race condition between:

- an event being processed creating a customer
- a web request making a charge that also needs to create a customer

But I think that should be addressed separately and that it's reasonable to create a customer record in the `link_customer` function.

Unrelated: @blueyed, would you be open to jumping onto the Pinax Slack team? @paltman and I regularly expedite discussions with a quick chat there, and it'd be cool to pick your brains on a couple of other projects etc.

**Comment by lukeburden** [comment]
@ticosax you'd be welcome to join the Slack team too, if you wanted!

**Comment by blueyed** [comment]
Just for reference, we use the following decorator, which could be adopted:

```
def recreate_missing_stripe_customer(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        callargs = inspect.getcallargs(f, *args, **kwargs)
        user = callargs['self']
        foo = callargs['foo']

        try:
            return f(*args, **kwargs)
        except stripe.error.InvalidRequestError as exc:
            if (exc.param == 'customer' and
                    exc.args[0].startswith('No such customer:')):
                customer, _ = user.get_or_create_customer(foo)
                customer.delete()
                return f(*args, **kwargs)
            raise exc
    return wrapper
```
