### ISSUE TITLE
What's Left

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-stripe#479]
Can we list what's left get a release out for at least partial Connect support, @blueyed @ticosax @lukeburden?

---

I believe that @lukeburden is running in production but probably not with the same features that @blueyed (and @ticosax) need.  Some things I think have been fixed.  There are others that still need to be brought into `master`.

I don't have a good sense of what will just be incrementally better versus what needs to happen to prevent regressions versus what needs to happen to make upgrades simpler and easier.  I'd like to avoid backward incompatible changes if at all possible between releases.

**Comment by paltman** [comment]
I'm thinking that #470 isn't something we should merge given all the other migration merges that have merged today.  Does that sound right?

**Comment by blueyed** [comment]
Yes, #470 needs to be updated: I've expected something like this just before the release, and then also using an actual squash migration, i.e. keeping the existing ones, but add one that squashes them (easier for users using master).

**Comment by paltman** [comment]
Nothing substantial left in:

https://github.com/pinax/pinax-stripe/pulls/blueyed or
https://github.com/pinax/pinax-stripe/pulls/ticosax

Does this mean the only thing remaining at least for the initial release with Connect support would be fixing up #470?

**Comment by blueyed** [comment]
You should compare https://github.com/pinax/pinax-stripe/pull/440/files.

The `UserAccount` model is another big one.

I've just tried to merge master back into next, but there were 5+ conflicts - mainly probably since I've squashed things when pushing them upstream and/or missing other fixes.

We also have https://github.com/pinax/pinax-stripe/pull/420 therein, which I've just closed out of frustration.

**Comment by ticosax** [comment]
Last piece will be `UserAccount` model, to keep relationship between `User` and `Customer` with connect.
We will extract it from #440 tomorrow. After that I believe that all migrations related to connect will be there.
There is still Coupons, but it can be postponed as it is not strictly related to connect.

Thank you for your support

**Comment by paltman** [comment]
thanks guys!  I appreciate it.  almost there!

**Comment by blueyed** [comment]
> I've just tried to merge master back into next, but there were 5+ conflicts

Hopefully solved: https://github.com/lock8/pinax-stripe/pull/54

**Comment by paltman** [comment]
@blueyed @ticosax I think we are good to go now, at least for the big release.  we can plan a smaller clean up release for a few weeks from now.  given the additional merges, what is everyone's thoughts on #470 (/cc @lukeburden)

**Comment by blueyed** [comment]
Yes, there should be an additional migration that squashes things.
Ours is this: https://github.com/lock8/pinax-stripe/pull/64

**Comment by ticosax** [comment]
If you feel inclined to, I just submitted #495, that covers some corner cases handling.
Anyway, it is time to make the squashing migration now 🍾

**Comment by lukeburden** [comment]
When you guys are done, I'd be happy to resubmit #470. I'm strongly in favour of a single migration for the addition of Connect support.

**Comment by paltman** [comment]
@ticosax merged

@lukeburden if you wouldn’t mind updating your PR with updated squashes, we can’t close up the milestone, tag, and release  

Fantastic work folks!

**Comment by lukeburden** [comment]
#470 has been updated. Looking forward to upgrading my projects to a real release of this instead of running off my fork :)

**Comment by blueyed** [comment]
@lukeburden 
Out of curiosity: how do you handle the migrations?  Wouldn't it have been easier for you also if there was a Django-squashed migration on top?
