### ISSUE TITLE
Add a financial dashboard with visibility into some basic metrics

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-stripe#49]
There are some good examples of this in some sites Eldarion has built that we should pull into DSP and open source and ship with the 2.0 version.

Summary by month for:
- transfers report
- charges report
- active customers by plan
- active subscriptions (total and by plan)
- cancellations (total and by plan)
- new subscriptions (total and by plan)
- churn (total and by plan / cancellation/total active subscription)

**Comment by paltman** [comment]
There are other services like https://baremetrics.com/ that do a fantastic job of this already and there is a lot of other things for us to get done first so bumping this from the 2.0 release. Might just close this ticket as WONTFIX sooner than later.

**Comment by jtauber** [comment]
While I'm 100% in support of punting this, I did want to note that there are use cases things like baremetrics *doesn't* work for which is why we had to do our own thing on at least one Eldarion site.
