### ISSUE TITLE
Error in _subscription_status.html -- line 9

### ISSUE THREAD

**Issue by surfer26th** [pinax/pinax-stripe#52]
Line 9 should be:
               {% if request.user.customer.current_subscription.plan and request.user.customer.card_kind %}

Currently, it is as shown below:
{% with request.user.customer.current_subscription as subscription %}
    {% if subscription %}
        {% if subscription.status == "active" %}
            <div class="alert alert-info">
                Your subscription will automatically renew in <strong>{{ subscription.current_period_end|timeuntil }}</strong>.
            </div>
        {% else %}
            {% if subscription.status == "trialing" %}
LINE 9-->                {% if request.user.customer.plan and request.user.customer.card_kind %}
                    <div class="alert alert-info">
                        Your free trial will end in <strong>{{ subscription.current_period_end|timeuntil }}</strong> after which you commence a <strong>{{ subscription.plan_display }}</strong> plan.
                    </div>
                {% else %}
                    <div class="alert alert-warning lead">
                        Your free trial will end in <strong>{{ subscription.current_period_end|timeuntil }}</strong> after which you will need to get a subscription to continue using the site.
                    </div>
                {% endif %}

**Comment by paltman** [comment]
template no longer exists
