### ISSUE TITLE
How do I handle the connect authorization for a new account?

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-stripe#522]
#### Issue Summary

I'm trying to setup a Standard connect flow but with `Customer`, `Account`, `UserAccount` models and actions of `customers.create` and `actions.create` neither looking like what I need, I'm not sure of how to handle the authorization redirect.  So far I have this:

```python
class ConnectAuthorize(LoginRequiredMixin, TemplateView):

    def get(self, request, *args, **kwargs):
        auth_code = request.GET.get("code")
        if auth_code:
            url = "https://connect.stripe.com/oauth/token"
            data = dict(
                client_id=settings.PINAX_STRIPE_CA_TOKEN,
                client_secret=settings.PINAX_STRIPE_SECRET_KEY,
                code=auth_code,
                grant_type="authorization_code"
            )
            response = requests.post(url, params=data)
            data = response.json()
            account = Account.objects.get_or_create(
                stripe_id=data["stripe_user_id"],
                user=request.user,
                stripe_publishable_key=data["stripe_publishable_key"]
            )
            accounts.sync_account(account)
            customers.create(self.request.user, account=account)
            messages.success(request, "Successfully connected to Stripe")
        else:
            messages.error(request, "There was an error connecting to your Stripe account")
        return redirect("pinax_stripe_connect")
```

This makes me feel like we are missing an action or that we need to update one of the existing actions.

In this view the `request.user` could already have a customer as they may be paying for the service that allows themselves to sell their wares, so I think we have to "get or create" their customer object.  

I think we should have an action like:

```python
accounts.connect(request.user, **data)
```

That handles the complexity for the site dev of determining:

1. if the user has a customer record already, if so using it, if not, creating it
2. creating the account object and syncing the details
3. doing something with the `UserAccount` object whatever that is

@ticosax @lukeburden @blueyed Thoughts?

**Comment by paltman** [comment]
In the scenario, I'd like to support, a `request.user` will be a `Customer` once they purchase.

Once they purchase, they'll have a customer created for them and be linked.

Once they've purchased, they'll then be able to use the Standard connect method and link their Stripe account so that they can charge their customers on our platform.  So during the connect phase, our customers will most likely already have a customer object and I need to create the `Account` object and link it to their customer object.

It's still not clear what the point of the `UserAccount` model is for but the actions seem to assume that that is populated to link the two, however, the customer object already has an FK to Account, which I'm thinking all I need to populate.

Any ideas?

**Comment by paltman** [comment]
I think I get what's going on now.

---

* `customer.stripe_account` is the stripe account id of the connected account that customer belongs to
* `UserAccount` allows for _account owner users_ to have more than 1 connected account and a mapping of their customers back to users
* The connecting of an Account by a user doesn't need to involve a customer at all:

```python
class ConnectAuthorize(LoginRequiredMixin, TemplateView):

    def create_account(self, user, stripe_user_id, stripe_publishable_key):
        defaults = dict(
            user=user,
            stripe_publishable_key=stripe_publishable_key
        )
        account, created = Account.objects.get_or_create(
            stripe_id=stripe_user_id,
            defaults=defaults
        )
        if not created:
            for key in defaults.keys():
                setattr(account, key, defaults[key])
            account.save()
        accounts.sync_account(account)
        return account

    def get(self, request, *args, **kwargs):
        auth_code = request.GET.get("code")
        if auth_code:
            url = "https://connect.stripe.com/oauth/token"
            data = dict(
                client_id=settings.PINAX_STRIPE_CA_TOKEN,
                client_secret=settings.PINAX_STRIPE_SECRET_KEY,
                code=auth_code,
                grant_type="authorization_code"
            )
            response = requests.post(url, params=data)

            data = response.json()
            self.create_account(
                request.user,
                data["stripe_user_id"],
                data["stripe_publishable_key"]
            )

            messages.success(request, "Successfully connected to Stripe")
        else:
            messages.error(request, "There was an error connecting to your Stripe account")
        return redirect("pinax_stripe_connect")
```

---

Am I thinking about this properly?

**Comment by lukeburden** [comment]
Hi @paltman - your first and third points are correct. I'll let @blueyed and @ticosax comment on the `UserAccount` model as they required it, but I think you're more or less on the money there too.

**Comment by blueyed** [comment]
UserAccount is mainly there for the `though` model, and that is only supported with m2m.
While it allows for multiple users per customer (or vice-versa), it typically is a single one only, but per Account.
