### ISSUE TITLE
admin: make all models read-only?

### ISSUE THREAD

**Issue by blueyed** [pinax/pinax-stripe#527]
A lot of models are registered with a long list of read-only fields.

Given the nature of pinax-stripe, we should maybe make all models read-only in the admin?!

If not, then saving a model in the admin should probably trigger an update to be sent to Stripe.
This might be a good next step, i.e. using Django's admin as a frontend to Stripe - but until then it seems that models should be made read-only in the admin.

**Comment by blueyed** [comment]
deleting models however turned out to be useful when cleaning data.

**Comment by paltman** [comment]
I agree.  Let's make them readonly.  I didn't realize that was possible.
