### ISSUE TITLE
How to uninstall pinax-stripe?

### ISSUE THREAD

**Issue by marcomayer** [pinax/pinax-stripe#543]
I would like to uninstall pinax-stripe from our Django instance but couldn't find any information on how to proceed. Is there a script for this maybe? If not can someone help me doing it the right way. Like how to remove the pinax-models in a clean way that doesn't screw up migrations. So what to actually remove and in what order. Besides the templates I found the pinax-stripe* SQL tables but would prefer to not try and manually delete these.

Thank you!

**Comment by mnieber** [comment]
I think it should be sufficient to delete any records from the `django_migrations` database table that mention pinax-stripe, and also delete any other pinax-stripe* table. If you have also removed pinax-stripe from your django site, everything should work (just speaking from general django experience, I have not used pinax). I would just back up the database and try it out. 

It's a good point about manual deletion, but django apps generally do not come with an automatic uninstall.

**Comment by KalobMTaulien** [comment]
@marcomayer Have you tried `pip uninstall pinax-stripe`? That should remove your files but it'll leave the tables in your database. For those, I like to manually delete those.

For Postgres do this:
`sudo su postgres` signs you in as the postgres user
`psql` will initiate postgres sql on your command line 
`\l` (that's a lowercase L) will list your databases 
`\c yourdatabase` will use your database
`\dt` will display your tables in your selected database
`DROP TABLE inserttablename;` drops the table. Don't forget the `;`

**Comment by marcomayer** [comment]
@mnieber @KalobTaulien thanks for your suggestions. We've gone the manual way and after removing the packages went into the DB and removed the obsolete tables etc. I think it's almost clean now, would be great if django modules always had a uninstall routine that takes care of this though.
