### ISSUE TITLE
site_media folder missing. css is not rendering in templates

### ISSUE THREAD

**Issue by mmack3540** [pinax/pinax-stripe#551]
#### Issue Summary

A short summary of the issue
I'm not sure if this is an issue with recent changes to the code or not. The site_media folder is missing.
Static files are not rendering in templates. Errors with npm run dev command. Ubuntu 16.04
I've downloaded and installed the code a couple years ago, and was able to run it with no issues. 
Following your README instructions, I got the errors below. npm and nodejs seemed to have installed correctly. 

malcolm@ubuntu:~/qb3/qb3$ npm run dev

  @ dev /home/malcolm/qb3/qb3
  concurrently --raw "./manage.py runserver" "npm run watch" "npm run dev:browser-sync"

sh: 1: concurrently: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ dev: `concurrently --raw "./manage.py runserver" "npm run watch" "npm run dev:browser-sync"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?npm ERR! A complete log of this run can be found in:
npm ERR!     /home/malcolm/.npm/_logs/2018-03-25T06_24_38_372Z-debug.log (edited)

---

_If this is a bug instead of a question or feature request, please fill out the sections below._

---

#### Steps to Reproduce

It's essential that you provide enough information for someone else to replicate the problem you're seeing. Simply describing something that's broken on your current project is not enough!

**Comment by grahamu** [comment]
@mmack3540 I think this ended up as an environment setup issue according to your [Slack comment](https://pinax.slack.com/archives/C11N6FU56/p1522007753000086). If that is true then I think you can close this issue as resolved. Thanks!

**Comment by mmack3540** [comment]
This issue was likely caused by a permission problem. It's closed. One more comment: In the docs, it would be nice to update the Getting Started section. It appears to skip over some important setup commands in the README.md file, the failure of which to execute in precise order may result in a permission problem. First in your environment, it's important to check to make sure npm and node.js is up to date:
$ npm -v
5.6.0
$ node -v
v9.9.0
Second, it's important to perform the following setup commands in precise order:
npm install
pip install -r requirements.txt
./manage.py migrate
./manage.py loaddata sites
npm run dev
Thanks!

**Comment by grahamu** [comment]
@mmack3540 Thanks for your suggestions. Just to be clear, by "docs" and "Getting Started", I presume you are talking about [this page](http://pinaxproject.com/pinax/pinax_starter_projects/)?

**Comment by mmack3540** [comment]
Yes, Graham. It would be nice to include it in the Getting Started sections of each project as well. And thanks again for your help!

**Comment by reillychase** [comment]
Same problem on Windows 10, but no solution. npm install fails, npm build fails, npm run dev fails. No dist folder in /static

C:\Users\Reilly Chase\Documents\Django\attempt4>npm -v
5.8.0

C:\Users\Reilly Chase\Documents\Django\attemp4>node -v
v9.10.0

**Comment by reillychase** [comment]
I got it working. I had to create the 'dist' dir inside /static otherwise 'npm build' would fail. I also had to 'npm install -g browserify'. Also I had to windows-ify the build command like '    "clean": "rmdir /s /q static\\dist && mkdir static\\dist\\js && mkdir static\\dist\\css && mkdir static\\dist\\images",' inside packages.json
