### ISSUE TITLE
Install fails on simplejson

### ISSUE THREAD

**Issue by reillychase** [pinax/pinax-stripe#553]
ImportError: cannot import name 'simplejson'

From what I've gathered, Django 2 doesn't support simplejson. Instead it should be replaced with `import json` and references to simplejson should be renamed to json

After I resolved this error I have a new error:
RuntimeError: Model class urlauth.models.AuthKey doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by denisemauldin** [comment]
I think you don't have modules installed that you need.  simplejson and json are not interchangeable.  You should `pip install simplejson` and make sure you've followed the steps in: http://pinax-stripe.readthedocs.io/en/latest/user-guide/getting-started/

**Comment by reillychase** [comment]
thanks I am trying again with simplejson installed now
