### ISSUE TITLE
Consider BIC in Stripe 2.0

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-stripe#578]
#### Issue Summary

A new version of the python library for Stripe was released and includes some backwards incompatible changes.

We should test and address them:

https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#200---2018-07-10

**Comment by blueyed** [comment]
https://github.com/pinax/pinax-stripe/pull/574
(1 week older than this issue already)

**Comment by blueyed** [comment]
For now I think `stripe-python` should be pinned at least.

**Comment by paltman** [comment]
@blueyed Sorry that I missed your PR.  I've been away from Pinax for a bit due to work commitments.  Looking to catch back up shortly but these seem priority.  My plan is to do the following:

1. Release a new minor version of `pinax-stripe` (v4.4.0) pinned to `stripe-python<2,>=1.7.9`
2. Merge #574 
3. Release a new minor version (since the change should be BC with integrations, I don't think it warrants a major version bump) of `pinax-stripe` (v4.5.0) pinned to `stripe-python>=2`

**Comment by paltman** [comment]
I suspect this the dependency caching in CI has prevented errors from triggering
