### ISSUE TITLE
Write Complete and Thorough Documentation

### ISSUE THREAD

**Issue by buddylindsey** [pinax/pinax-stripe#59]
Are there any plans for more documentation? I have been reading through code off and on for the last few days, working on side project. There is a lot of good code, but it is highly opinionated so I am not sure how to use some of it because I don't understand some of those opinions. Granted I am still learning about stripe as well.

I feel like about the only thing I can re-use is the webhooks code, but other than that I am on my own. A couple of things that I have been trying to figure out:

1) Using stripe.js instead of Checkout
2) Re-using templates, I have been having a hard time trying to use the templates you provide. Is it best to just copy them out and re-implement?
3) On the opinionation what is the best practice eldarion sees for the urls? doing everything on the root or something else?

There is a lot of good work here, but I am spending time figuring out "how" to use it over being able to use it.

I also see you are about to do a version 2.0 release so maybe I just found it at the wrong time. lol.

**Comment by paltman** [comment]
See also #50 and #26 and #37 and #53 and #61

**Comment by paltman** [comment]
I'm struggling with how to judge if this ticket is ever done. I mean I think documentation can always be made more thorough and added to. At the same time, what I currently have now for `pinax-stripe` still needs a lot more, but I think it's sufficient for a 2.0 release.  Therefore, I think what's left I'll just document here explicitly and then create separate issues for:

* eCommerce walk through / guide (#203)
* Software as a Service walk through / guide (#204)
* Reference Docs
    * Actions (#205)
    * Management Commands (#206)
    * Templates (#207)
    * Forms (#208)
    * HookSets (#209)
    * Managers (#210)
    * Middleware (#211)
    * Mixins (#212)
    * SIgnals (#213)
    * URLs (#214)
    * Utilities (#215)
    * Views (#216)
    * Webhooks (#217)
* History (#218)
* Release Notes (#219)
