### ISSUE TITLE
Documentation for single payment

### ISSUE THREAD

**Issue by tsurantino** [pinax/pinax-stripe#61]
Is there any documentation on how to process a *single* payment using this plugin or is it purely for subscriptions?

You mention that this is a great plugin for one-off payments but there is literally no single piece of documentation for making a one-off payment with a variable amount. From a look at  the code, I can only imagine that the "one-off" payment refers to paying a one-time "subscription". 

I apologize in advance if I've missed something.

**Comment by adamduren** [comment]
Is there any way to create a one-off charge without a customer? Looking at the API this should be possible by excluding `customer` but in `pinax.actions.charges.create` `customer` is a required parameter. Would it work to pass `None` to please python?
