### ISSUE TITLE
Add Django 3.0 support

### ISSUE THREAD

**Issue by RevolutionTech** [pinax/pinax-stripe#638]
**Is your feature request related to a problem? Please describe.**
I'm trying to upgrade my project (which has `pinax-stripe` as a dependency) from Django 2.2 to 3.0, but it looks like `pinax-stripe` does not yet support Django 3.0.

More specifically, `pinax/stripe/models.py` has the following import:
```python
from django.utils.encoding import python_2_unicode_compatible
```
but this was [removed in Django 3.0](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) due to Python 2 EOL.

**Describe the solution you'd like**
Since Python 2 has reached EOL, I think it would be acceptable to drop support for it. If that was done, this decorator wouldn't be necessary.

**Additional context**
It could be that there are other incompatibilities with Django 3.0, I have not checked beyond this issue.

Thank you for this project, I have found it very helpful!

**Comment by KatherineMichel** [comment]
@RevolutionTech Glad you have found this project helpful! We have a new release in process that will drop Python 2. Both @paltman and @mfonism have mentioned making updates. I'm not sure when it will be completed, but it is on our radar!

**Comment by goromachine** [comment]
There are any news about Django 3 support? 
Should I downgrade my Django project to Django 2 in order to be able to implement stripe with your package? Seems the best stripe package for Django.

Thank you, I'm looking forward to use pinax-stripe on my project.

**Comment by KatherineMichel** [comment]
@goromachine Unfortunately, there is not any news at the moment. @paltman and @mfonism have not been able to get to it and I'm finishing up the other parts of the release.

**Comment by instantrad** [comment]
What is the update?

**Comment by yeisonvargasf** [comment]
Hi, any update about this issue? is there any help needed?

**Comment by paltman** [comment]
This is now done for both `pinax-stripe-light` (soon to launch) as well as the `original` branch (see #645 for announcement on the split)
