### ISSUE TITLE
Changed API logic in Customer.cancel() breaks logic elsewhere

### ISSUE THREAD

**Issue by dougvk** [pinax/pinax-stripe#86]
sample response from stripe API on cancel request:

```
In [12]: user.customer.stripe_customer.cancel_subscription(at_period_end=True)
Out[12]:
<StripeObject subscription at 0x3c5fc90> JSON: {
  "cancel_at_period_end": true,
  "canceled_at": 1377577750,
  "current_period_end": 1380254784,
  "current_period_start": 1377576384,
  "customer": "cus_2PrZAZ0payaXid",
  "ended_at": null,
  "object": "subscription",
  "plan": {
    "amount": 119900,
    "currency": "usd",
    "id": "realtime",
    "interval": "month",
    "interval_count": 1,
    "livemode": false,
    "name": "Realtime",
    "object": "plan",
    "trial_period_days": 2
  },
  "quantity": 1,
  "start": 1377576384,
  "status": "active",
  "trial_end": null,
  "trial_start": null
}
```
notice status says 'active', but in ```_subscription_status.html``` (and maybe elsewhere in your code?) you check ```subscription.status``` when you should be checking ```subscription.cancel_at_period_end```

**Comment by paltman** [comment]
This is going to depend on the settings of the stripe account (see [documentation](https://stripe.com/docs/guides/subscriptions#canceling-subscriptions)). I think ultimately this is up to the site developer for how they want to display things in their template.
